Repository Jungle-TechLab/GTL_W07_T7, pull requests merged in 2025-04, with the labels that each got.

#1 프로젝트 정리
  EngineSIU/EngineSIU.sln
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/SceneMgr.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SphereComp.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/TextComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/ResourceMgr.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/EditorRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/Audio.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/BufferHelpers.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/CommonStates.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/DDSTextureLoader.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/DirectXHelpers.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/Effects.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/GamePad.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/GeometricPrimitive.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/GraphicsMemory.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/Keyboard.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/Model.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/Mouse.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/PostProcess.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/PrimitiveBatch.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/ScreenGrab.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/SimpleMath.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/SimpleMath.inl
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/SpriteBatch.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/SpriteFont.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/VertexTypes.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/WICTextureLoader.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/DirectXTK/Include/DirectXTK/XboxDDSTextureLoader.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imconfig.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_demo.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_draw.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_impl_dx11.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_impl_dx11.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_impl_win32.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_impl_win32.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_internal.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_tables.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_widgets.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imstb_rectpack.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imstb_textedit.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imstb_truetype.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Json/include/Json/json.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/tinyfiledialogs/include/README.txt
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/tinyfiledialogs/include/tinyfiledialogs.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/tinyfiledialogs/include/tinyfiledialogs.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/EngineSIU.vcxproj.filters
Labels: size/XXL

#2 Refactor and optimize functions, and add light property accessors
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/JungleMath.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/JungleMath.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector4.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/AmbientLightActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/DirectionalLightActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/DirectionalLightActor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/FireballActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/FireballActor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/HeightFogActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/PointLightActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/PointLightActor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/SpotLightActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/SpotLightActor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ActorComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/AmbientLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/AmbientLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/DirectionalLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/DirectionalLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/LightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/LightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/PointLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/PointLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/SpotLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/SpotLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ProjectileMovementComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FLoaderOBJ.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FLoaderOBJ.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/Texture.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Actor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/InteractiveToolsFramework/BaseGizmos/TransformGizmo.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/EditorRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/EditorRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.h
Labels: size/L

#3 Add shader hot reload functionality
  .github/workflows/pr_build_test.yml
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/BillboardRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/BillboardRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CompositingPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/EditorRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/EditorRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/FogRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/FogRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/GizmoRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/GizmoRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/LineRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/LineRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.h
Labels: size/XXL

#4 Feat/point light shadow
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Contents/ShadowLab.scene
  EngineSIU/EngineSIU/Contents/ShadowLab1.scene
  EngineSIU/EngineSIU/Contents/ShadowLabG.scene
  EngineSIU/EngineSIU/Contents/ShadowLabMany.scene
  EngineSIU/EngineSIU/Contents/ShadowLabb.scene
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/JungleMath.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/JungleMath.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Matrix.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/LightDefine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/ShadowDefine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/DirectionalShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/DirectionalShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/PointLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/PointLightShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.h
  EngineSIU/EngineSIU/Shaders/DepthBufferPixelShader.hlsl
  EngineSIU/EngineSIU/Shaders/DepthBufferVertexShader.hlsl
  EngineSIU/EngineSIU/Shaders/DepthOnlyVertexShader.hlsl
  EngineSIU/EngineSIU/Shaders/DepthVisualize.hlsl
  EngineSIU/EngineSIU/Shaders/Light.hlsl
  EngineSIU/EngineSIU/Shaders/LightDepthOnlyVS.hlsl
  EngineSIU/EngineSIU/Shaders/StaticMeshPixelShader.hlsl
  EngineSIU/EngineSIU/editor.ini
  EngineSIU/EngineSIU/imgui.ini
Labels: size/XXL

#6 Feat/multi light shadow
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/LightDefine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/ShadowDefine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/DirectionalShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/DirectionalShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/PointLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/PointLightShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.h
  EngineSIU/EngineSIU/Shaders/Light.hlsl
  EngineSIU/EngineSIU/Shaders/LightDepthOnlyVS.hlsl
Labels: size/XXL

#7 Enhance shader hot reload and implement thread-safe queue
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/BackgroundShaderCompile.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/BackgroundShaderCompile.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/BackgroundShaderCompileData.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/BackgroundShaderCompileData.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/ShaderCompileUtility.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/ShaderCompileUtility.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/ShaderFileMetadata.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/ShaderFileMetadata.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/ShaderMetadataPtr.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderHotReload/ShaderMetadataPtr.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/Queue.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/TSafeQueue.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.h
Labels: size/XXL

#8 fix: Directional Light 에러 2개 수정
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/DirectionalShadowMap.cpp
Labels: size/S

#9 Feat/depth map visual
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/PointLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/PointLightShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.h
  EngineSIU/EngineSIU/Shaders/DepthCubeVisualize.hlsl
Labels: size/L

#10 refactor: light 정보 전달 Constant 말고 Structure로 하도록 변경
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/LightDefine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.h
  EngineSIU/EngineSIU/Shaders/Light.hlsl
Labels: size/L

#11 Add shader metadata management and GPU stats enhancements
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderCompile.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderCompile.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderCompileData.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderCompileData.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderCompileUtility.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderCompileUtility.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderFileMetadata.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderFileMetadata.h
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderMetadataPtr.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/ShaderCompileUtils/ShaderMetadataPtr.h
  EngineSIU/EngineSIU/Engine/Source/Editor/LevelEditor/SLevelEditor.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/LevelEditor/SlateAppMessageHandler.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/PrimitiveDrawBatch.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/SceneManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/SceneMgr.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectFactory.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectHash.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectHash.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/ResourceMgr.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Actor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/World/World.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/InteractiveToolsFramework/BaseGizmos/TransformGizmo.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/EditorRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/GizmoRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDBufferManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDBufferManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/D3D11RHI/DXDShaderManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/RawInput.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/RawInput.h
Labels: size/XL

#12 Feat/vsmgogo
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/ShadowDefine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/UpdateLightBufferPass.cpp
  EngineSIU/EngineSIU/Shaders/Light.hlsl
  EngineSIU/EngineSIU/Shaders/VSMGenerationPS.hlsl
  EngineSIU/EngineSIU/editor.ini
Labels: size/XL

#13 fix: Depth Buffer는 하나여도 충분하므로 VSM이더라도 같은 Depth 버퍼 쓰도록 수정
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/SpotLightShadowMap.h
Labels: size/M

#14 Refactor/widechar migration
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/SceneManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/String.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/String.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/StringConv.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Traits/IsCharType.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/NameTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.h
Labels: size/M
